### ISSUE TITLE
Could you have some instructions to execute this repository?

### ISSUE THREAD

**Issue by xiaoqun-growing** [DCMMC/EBSNN#2]
I just clone this repository, however, I caught some errors when I execute **run.sh**, the error of print as follows:

`Start instance 1 of lstm and bilstm
Start instance 2 of lstm and bilstm
Wait for 31171
Traceback (most recent call last):
  File "./train.py", line 124, in <module>
    segment_len=SEGMENT_LEN, shuffle=SHUFFLE)
  File "/data/xq/ML_ids/EBSNN/datapreprocessing.py", line 371, in get_dataloader
    shuffle=shuffle)
  File "/data/xq/ML_ids/EBSNN/datapreprocessing.py", line 135, in _get_dataloader_packet
    driver='mpio', comm=MPI.COMM_WORLD)
  File "/root/miniconda3/envs/xq_py365/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/root/miniconda3/envs/xq_py365/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (File does not exist, error stack:
ADIOI_UFS_OPEN(39): File data/20_header_payload_all.hdf5 does not exist)
`
Thanks for your consideration!

**Comment by DCMMC** [comment]
Because the preprocessed `.hdf5` or `.traffic` files are too large, we only publish the original `.pcap` files. You need to preprocess these pcap files into a `.traffic` file. In the `.traffic` file, each line represents a preprocessed packet. For example, `reddit//tcp0//0 45 10 00 48 00 00 40 00 40 ...`. To preprocess, you need remove irrelative packets (e.g., ARP, ICMP, DNS) and mask some fields according to the paper. `.hdf5` files are just another form of `.traffic` files, you can read the [codes](https://github.com/DCMMC/EBSNN/blob/main/datapreprocessing.py#L130).
